/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package esa.mo.nmf.ctt.services.common;

import esa.mo.common.impl.consumer.LoginConsumerServiceImpl;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.ccsds.moims.mo.common.login.body.LoginResponse;
import org.ccsds.moims.mo.common.login.structures.Profile;
import org.ccsds.moims.mo.mal.MALException;
import org.ccsds.moims.mo.mal.MALInteractionException;
import org.ccsds.moims.mo.mal.structures.Identifier;

/**
 *
 * @author Andreea Pirvulescu
 */
public class LoginConsumerPanel extends javax.swing.JPanel {

    private final LoginConsumerServiceImpl serviceCommonLogin;
    private final LoginTablePanel loginTable;
    private boolean authenticationStatus = false;
    public String[] data = new String[3];

    /**
     * Creates new form LoginConsumerPanel
     *
     * @param serviceCommonLogin
     */
    public LoginConsumerPanel(LoginConsumerServiceImpl serviceCommonLogin) {
        initComponents();
        this.serviceCommonLogin = serviceCommonLogin;
        loginTable = new LoginTablePanel(serviceCommonLogin.getCOMServices().getArchiveService());
    }

    public boolean isAuthenticated() {
        return authenticationStatus;
    }

    public void checkData() {
        Identifier username = new Identifier(this.data[0]);
        Long role = Long.valueOf(this.data[1]);
        String password = this.data[2];

        Profile profile = new Profile(username, role);

        LoginResponse loginResponse;
        try {
            loginResponse = this.serviceCommonLogin.getLoginStub().login(profile, password);
            if (loginResponse != null) {
                authenticationStatus = true;
            }
        } catch (MALInteractionException ex) {
            Logger.getLogger(LoginConsumerPanel.class.getName()).log(Level.SEVERE, null, ex);
        } catch (MALException ex) {
            Logger.getLogger(LoginConsumerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JButton();

        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login)
                .addContainerGap(266, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here: 
        LoginFrame lfr = new LoginFrame(this);
        lfr.setVisible(true);
    }//GEN-LAST:event_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton login;
    // End of variables declaration//GEN-END:variables
}
